version: '3'

services:
  openai-slack-bot:
    image: ghcr.io/jack482653/openai-slack-bot:latest
    restart: always
    environment:
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
    - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
    - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
